### ISSUE TITLE
Can't record into buffers after clearing them (introduced with norns update 220129?)

### ISSUE THREAD

**Issue by MentalSandal** [dndrks/cranes#3]
Hey Dan!

I noticed that since norns 220129, clearing the buffers means we can't re-record again. Pressing K2 displays the crane, but the transport/softcut poll isn't running, so no sound gets recorded.
Commit [e2e1188](https://github.com/dndrks/cranes/commit/e2e11880296f49391bb020eac096f7ff5687fe79) exhibits the same issue with 220129 and 220306 but is working perfectly fine with 210927.

**Comment by dndrks** [comment]
hihi!
woop, totally didn't see this till now, very many apologies + thank you for the quick fix!! holy moly :)
i've got a v3 in the works, almost done, so this will be a fantastic bridge <3
